receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  file:
    path: /traces/run.json
    rotation:
      max_megabytes: 100

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file]
